### PR TITLE
Issue #29 - Update styles to match guidelines

### LINKED ISSUE #29: Update Pages to Meet style outline
update all the existing pages to meet the newly created style outline. Should be as easy as adding the style created in issue #20

### PR DESCRIPTION
**Pull request by jbuzzell**
Some styles, such as those to do with the current game page nav, have
not been changed. These styles do not match with the guidelines, but
require further consideration or complete redesign.

closes #29

### CODE REVIEW

**Comment by jbuzzell** [comment]
specifically left out the game page nav from style updates. i would rather see this as a dropdown in the navbar than a feature on the page.

**Comment by jbuzzell** [comment]
@CSI-280/web-people anyone who feels so inclined to review is welcome. sorry this is coming in late.

**Comment by JakeCapra** [comment]
I liked the bigger gamenav buttons better. I do like the space you added on the left, however.

**Comment by jbuzzell** [comment]
oh wow, i didn't even mean to change that. i'll fix that and commit & i imagine it should be good to go after that

**Comment by jbuzzell** [comment]
updated to make the buttons bigger and to make the game layout look a little better. i used css grid this time too so it should be more responsive.

**Comment by JakeCapra** [comment]
Looks good, can you make the whole rectangle a link, and not just the text? Also, I think that this broke the tic tac toe reset button, it's not under the board anymore: 
image

**Comment by jbuzzell** [comment]
yeah, i can fix that. 

oh jesus i forgot about the reset button. i'm not actually sure how that's rendered, i'll give it a look.

**Comment by jbuzzell** [comment]
ok, fixed some of the issues. i couldn't get the reset button to be left aligned with the board so i centered it.

should we make the button red when you lose and green when you win? i just have it following the basic styleguide right now

**Comment by jbuzzell** [comment]
@CSI-280/web-people bump

**Comment by A-Waters** [comment]
Uh I mean if it's not a lot of work it might be a nice touch, but we should be consistent over the website.

**Comment by jbuzzell** [comment]
@CSI-280/web-people this still hasnt been formally approved, can someone look at it? if i don't hear back i'll probably merge by like 3 or something along with any other style updates for the presentation

**Comment by A-Waters** [comment]
You haven't requested anyone to review it... but there are some merge conflicts. @jbuzzell

**Comment by jbuzzell** [comment]
yeah i can handle the merge conflicts. my bad i didn't actually assign any reviewers, i just tagged everyone.

**Comment by jbuzzell** [comment]
ignore this, i'm going to include the changes in my pr for #69

**Comment by jbuzzell** [comment]
as #77 implements these  changes but better i'm closing this

**Pull request closed without merging**
