### PR TITLE
issues #13 #20

### LINKED ISSUE #11: Create basic home page
To be done only once we've got all the setup done, so that we can build this off of react and stuff.  We just need a starting point for the user interface, a splash screen.  Take a look at the design layout from issue #2  marked home page and go off of that.  Should include:

- nav bar
- links to other pages such as points and games (even if the don't go anywhere yet)
- link to home page in form of title
- blank space for our icon and maybe a little description

don't need to implement how the widget/playlist bar will work, so leave that out for now.

### LINKED ISSUE #13: Create a Navbar
I mentioned this in our first meeting, but since our project is music-based, it would be cool if we could have a music player in the navbar, so music was playing on every page you visited, and it would be continuous. Last.fm does something similar:
image
https://wireframe.cc/AxfMXd
The wireframe I made uses some of what Lenora made in issue #2

### LINKED ISSUE #20: Create CSS rules for React components

### LINKED ISSUE #27: Add jquery to readme
I decided to use [jquery,](https://jquery.com/) which helps with selecting elements in js/html, for the tic-tac-toe game.  It is easy to use and totally optional on a component-by-component basis, meaning no one has to learn it or use it if they don't want to, but it still needs to have documentation regardless.  Since I'm the one who implemented it, I'll do the documentation, but I just needed this reminder in here and as a formal way of saying that this is being added to the project.

### PR DESCRIPTION
**Pull request by jbuzzell**
this PR will:

- add navbar to site

- add styles to navbar

- add overarching site styles as outlined in #8

### CODE REVIEW

**Comment by A-Waters** [comment]
is this still a work in progress?

**Comment by jbuzzell** [comment]
yes! my bad, made this too early

**Comment by JakeCapra** [comment]
Ok. This is good to go now. Just note that the player is not implemented yet, and we do not have dropdowns either.

**Review by NathanDiMauro — APPROVED** [review]
Looks good. Great idea to move the games navigation to it's own document

**Review by A-Waters — APPROVED** [review]
Looks Good, +1

**Pull request merged**
