### PR TITLE
Styled TicTacToe

### PR DESCRIPTION
**Pull request by NathanDiMauro**
Styled the TicTacToe game and fixed a few bug with it.

### CODE REVIEW

**Comment by lenora4321** [comment]
I love, love, love the music notes! My only comment would be to mess with the reset button.  It changes nice and red when you win or tie, but it's white and says nothing otherwise.  I think it should at least say something, or you can mess with the js a bit to make it say "reset".  Otherwise, looks great!

**Review by JakeCapra — APPROVED** [review]
Looks clean, I like it. Nice work

**Comment by NathanDiMauro** [comment]
@lenora4321 all done. I simply made the button invisible when the game is being played.

**Review by JakeCapra — APPROVED** [review]

**Comment by NathanDiMauro** [comment]
Solved Issue #34

**Pull request merged**
