### PR TITLE
Google sign in

### PR DESCRIPTION
**Pull request by JakeCapra**
Implemented the Google Sign-In API. This pr resolves issue #38.
Currently, I have it set up to record a user's **Full Name**, **First Name**, **Last Name**, **Email**, **Google ID**, and **Profile Pic (URL)** (these are all variables, see navbar.js for the full object).

**Things to note about this change**:
- Package.json has been modified, so make sure you check the readme.
- We also have one more dependency to worry about now. To install it, just do
`npm install react-google-login` (info also in the readme)
- navbar.js has been modified so that the userInfo object is passed into each page. Before a link looked something like this:
 `<p><Link to="/">Home</Link></p>`
  now a link will look something like this:
 `<Link to={{pathname:"/", state: {user}}}>Home</Link>`. 
`user` is the object that has all the user info 
_these are link from navbar.js_
- The login item on the navbar has been replaced by a profile page, which displays a user's profile pic, name, email, and points associated with their account. If someone is not logged in, then a log in button will show up, and will allow the user to log in.

**Accessing the user object from a page**: 
- In order to access a users information, you must change the component to a class (see profile.js). 
- Once the component is a class, you can access the data with `this.props.location.state.user.VARIABLE` (also see profile.js).
- If you wanted to update a users point amount (locally, and only for the current session), you could do `this.props.location.state.user.points += x`

Currently, there is no way to sign out of an account. I could implement it later if we think it's necessary.
**Make sure you look at the updated readme if something is not working for you!!**

### CODE REVIEW

**Comment by A-Waters** [comment]
actually well done, but do we want to move the user info into possibly a client.js? e.g. something like the Spotify client and the user client I currently have in a merge request #52 . I'm asking because while I understand the code it might be worthwhile to move some stuff around but you know the code better than me.

**Comment by JakeCapra** [comment]
I would not know how to do it. I am treating navbar.js as the "home" for the user data, so that every page has access to the users info. What we could do is pass the user object to client.js.

**Review by A-Waters — APPROVED** [review]
I think that's the move but lets merge first

**Review by jbuzzell — APPROVED** [review]
looks good, nice job!

**Pull request merged**
