### PR TITLE
Added player to navbar

### LINKED ISSUE #36: Create the Player Feature.
This will be added to the Navbar. It is probably best to use an API for this and make it a react component so it's easy to add it to the navbar. 

We could SoundCloud's Player API - [Documentation ](https://developers.soundcloud.com/docs/api/html5-widget#playground)| [Demo](https://w.soundcloud.com/player/api_playground.html)

 If anyone knows of any other good API's to use feel free to link it.

### PR DESCRIPTION
**Pull request by JakeCapra**
Add player to navbar and re-styled navbar. This resolves #36 .

### CODE REVIEW

**Comment by JakeCapra** [comment]
this has been sitting here for a few days, maybe if I change the reviewers someone will approve it.

**Comment by jbuzzell** [comment]
i'll give it a look tonight, sorry i haven't gotten around to it. i'll be more prompt with review in the future

**Comment by JakeCapra** [comment]
don't worry about it, i think we all got a lot going on rn

**Comment by jbuzzell** [comment]
looks good to me. nice song choice. did you add the hover states for the links? the transitions look good, but i'd suggest we go with the orange (or even just white) for the hover color.

**Review by jbuzzell — APPROVED** [review]

**Comment by JakeCapra** [comment]
I changed it to white

**Comment by JakeCapra** [comment]
@thomasszp what do you think?

**Pull request merged**
