### PR TITLE
styled games page

### PR DESCRIPTION
**Pull request by lenora4321**
Did some nice styling for the game hub page to close issue #35.  The buttons are now nicer and have a little animation when you hover over them.  We will need to decide if we want the games hub to show up below the games on every page as it does now or not, but the styling itself is done.

### CODE REVIEW

**Review by NathanDiMauro — CHANGES_REQUESTED** [review]
I think that the entire button on the game navigation bar should act as a link not just the words. I like the style alot though. Also maybe pull the changes I made to the tictactoe style to make sure the merge dosen't mess that up, but that is something we can resolve later if you don't want to do it. 
- [ ] Update nav boxes
- [ ] Pull tictactoe style

**Review by JakeCapra — CHANGES_REQUESTED** [review]
I think that [gamenav should be at the top](https://wireframe.cc/0du9kg), and the game you're playing below the gamenav. Or you could have[ half of the page be the gamenav](https://wireframe.cc/heQx7S), and the other half the be the game you're playing. The game you clicked on would render in the game section when you clicked the button.

**Review by NathanDiMauro — CHANGES_REQUESTED** [review]
I like the NavBar on the side alot. I dont think it should be up top. I would like the issue of the navbar not actually working on the whole box to be fixed, however. Also now that the pull request on the tictactoe restyle has gone through I think you should pull the changes to that and make sure they work and don't cause a merg conflict. 

- [ ]  Update nav boxes
- [ ]  Pull tictactoe style

**Comment by JakeCapra** [comment]
@NathanDiMauro you mean you want the whole box to be a link, not just the text?

**Comment by lenora4321** [comment]
Alright, check it out now.  I made the buttons encompass the whole td, incorporated the new tic-tac-toe styling, and moved the bar to the side. :)

**Review by NathanDiMauro — APPROVED** [review]
Beautiful!!!

**Review by JakeCapra — APPROVED** [review]
Looks good

**Comment by lenora4321** [comment]
If you're referring to the game hub title above the buttons, nope.  I didn't put that there, I just rolled with it

**Pull request merged**
