### PR TITLE
issues #33 #31 #46 #47

### LINKED ISSUE #31: Prototype Django database models
starting with something like UserData that stores the user's spotify uid (could be either int or string), and their pub/private access keys (string)

https://docs.djangoproject.com/en/3.0/topics/db/models/

### LINKED ISSUE #33: Create link between frontend & database using API calls
https://www.django-rest-framework.org/

- [x] create GET requests to gather data from django models #31 using Django REST API & confirm data retrieval by printing to console.

- [x] create POST requests that update django data & check that data was properly posted in the django admin page

### LINKED ISSUE #46: Review/Suggest for data models
I created a basic data model for user data with Django/Rest framework, as per [Jake's issue](https://github.com/CSI-280/MusicGames/issues/31#issue-590627652). It'll look something like this:

User
-ID (So users can be uniquely identified, stored as string. Our primary key, if anyone remembers that from Database Management. Max length abt 20~~) 
-Public Access Key (String, max length 35)
-Username (Probably won't need to be much longer than 20 characters?)
-Points (Integer)

Any suggestions for things to add? [This site](https://docs.djangoproject.com/en/3.0/topics/db/models/) was very helpful as a refresher on database models. 

It's in backend\src\djreact\models.py if anyone wants to add any additional models or change anything to this model. Otherwise, suggest them here and I'll work on em myself!

### LINKED ISSUE #47: Integrate the Database model into the site
We need to implement it so we can actually begin storing users.

### PR DESCRIPTION
**Pull request by A-Waters**
This covers a bit of the issue since we have 4 that are very similar in their end goal
#33 #31 #46 #47

As of making this pull request, the google login isn't implemented, so for rn the google ID I'm using is just a random number. Also, I'm hoping google can help Handel security.

time to break this down

## backend
first thing I did was remove articles 
Okay in basically there is now another model known as 'user', which holds the following properties:
* google id (primary key)
* public access key
* username
* points

there are now 4 more endpoints with corresponding methods each having thier own view: 
* 'user/' (get)
* 'user/<pk>' (get)
* 'login/' (post)
* 'setUserData/' ( post)

## frontend
new file ----> userClient.js
how this works is very similar to the Spotify API.

#### how to use  :
(example can be found in list.js componentDidMount())

its pretty self explanatory but the idea is you take the id number we get from google, and we put it into the login function. Here a user will be created if there is already not a preexisting user. after doing this you can make calls to the user client for setting and getting data as listen in the userClient.js

#### you will have to have the backend running for this to work

Lmk if you have questions, confusion, or problems.

### CODE REVIEW

**Comment by jbuzzell** [comment]
i'd like to leave this in limbo a minute and merge #53 into it once it gets approved just to see if the two play nice with each other.

**Comment by A-Waters** [comment]
Okay so now in profile.js there is some extra code, to add the data in userClient.js so we can have all user data in one place. I didn't touch how data was stored in the navbar tho because I didn't want to screw anything up. seems to work fine together as far as I can tell. Also made the google id the primary key for our databsae.

**Comment by JakeCapra** [comment]
Nice. You know that there is a full name variable right?

**Comment by A-Waters** [comment]
Yeah, I wasn't sure what was best there, but I didn't think we need like a whole extra variable for just two other variables combined. easy fix tho if we want it.

**Comment by A-Waters** [comment]
Feel free to merge when ready. Code working

**Review by jbuzzell — APPROVED** [review]
works for me. make sure we run a migration on the backend (manage.py migrate) when we push to master just to make sure everything's synced up

**Review by JakeCapra — APPROVED** [review]
Nice work, approved.

**Comment by A-Waters** [comment]
@lenora4321

**Comment by lenora4321** [comment]
workin on it

**Comment by lenora4321** [comment]
Looks clean, login works, good job!

**Review by lenora4321 — APPROVED** [review]
Nice!

**Pull request merged**
