### PR TITLE
Initial games

### PR DESCRIPTION
**Pull request by lenora4321**
I have implemented tic-tac-toe in a react component.  You can play against the AI, and it will stop you when someone has won or tied.  Right now it's just sitting on the homepage, but sine it is a component, it can be moved easily to a games page once we have it.  It also does not add points yet, since I don't know how far our database is, but adding that feature shouldn't be too hard.  Play a few rounds and tell me what y'all think.

### CODE REVIEW

**Comment by A-Waters** [comment]
I don't really see anything particularly wrong with it, but I am confused... but it's alright. I think it's fine, its just a lot of files were changed that I don't think you edited personally... but I think that is just the dependencies updating? and the .pyc files recompiling? What files did you edit?

**Comment by lenora4321** [comment]
I'm not sure about the individual files besides app.js and the tic-tac-toe files (js and css), but I did totally forget to mention that I decided to use [jquery](https://jquery.com/) for my js coding. It makes manipulating elements a lot easier and is totally optional file by file, but it is included on the tic-tac-toe page.  If this pull request get approved, I will have to add documentation for it to the readme, since it is another library, but no one else has to use it unless they want to, and it is installed easily with npm.

**Review by A-Waters — APPROVED** [review]
Sounds good, just make sure to add that to the read me.

**Review by NathanDiMauro — APPROVED** [review]
Great work

**Pull request merged**
