### PR TITLE
README Formatting changes, and added documentation for django and react

### PR DESCRIPTION
**Pull request by JCastaner**
changed formatting for our Django/React section and added links to documentation for both. Changed some vocabulary around as well.

### CODE REVIEW

**Comment by JakeCapra** [comment]
We just need to add how to set up and initialize the project with Django and React. I added a setup section in the readme but I don't actually know how to set it up. I followed the instructions from #15, but could not get it. If someone knows how to do it, let me know, and we can put those instructions in the readme.

**Comment by A-Waters** [comment]
@JakeCapra Where were you getting caught? Were you having issues with the front side or back side (Django or react) (pip or npm)? Possibly you were getting caught on dependencies, I updated #15 to maybe help resolve this issue.

**Comment by A-Waters** [comment]
@JakeCapra 
as for the instructions, it should follow the lines of git cloning the project and cd into it.
```
git clone https://github.com/CSI-280/MusicGames.git
cd Musicgames
```
after that, they should install dependencies
```
pip install django djangorestframework virtualenv pep8 autopep8 pylint django-cors-headers
npm install axios
cd .\frontend\gui
npm install
````

after that they should be able to run the files

for the front side
```
cd .\frontend\gui
npm start
```

and for the back side in a new terminal in the project directory
```
python backend\src\manage.py runserver
```

**Comment by JakeCapra** [comment]
@TAwc thanks, that really clears thing up, I'll add those to the readme.

**Comment by A-Waters** [comment]
note this is after we are merged into master. for it to get currently working you have to be on branch 'alex'

**Comment by JakeCapra** [comment]
Ok. After messing the formatting up like 3 times, it's done.

**Review by A-Waters — APPROVED** [review]
looks good +1

**Review by NathanDiMauro — APPROVED** [review]
Looks good

**Pull request merged**
